project:
  type: website
  resources:
    - .well-known
editor: source
lang: en
language:
  title-block-published: "Event Date"
  title-block-author-single: "Speaker"
website:
  title: "R-Ladies Vienna"
  favicon: logo.png
  site-url: https://rladies-vienna.github.io
  twitter-card: true
  open-graph: true
  navbar:
    title: "R-Ladies<br>Vienna"
    search: false
    # pinned: true
    right:
      - href: about-us/index.qmd
        text: ABOUT US
      - href: join-us/index.qmd
        text: JOIN US
      - href: events/index.qmd
        text: EVENTS
  page-footer: 
    left: R-Ladies Vienna, 2025  
    center: This website is built with [Quarto](https://quarto.org/) and [GitHub](https://github.com/rladies-vienna/rladies-vienna.github.io).
    right: '[{{< fa brands meetup title="Meetup">}} Meetup](https://www.meetup.com/rladies-vienna/) | [{{< fa brands mastodon title="Mastodon">}} Mastodon](https://mastodon.social/@RLadiesVienna) | [{{< fa brands bluesky title="Bluesky">}} Bluesky](https://bsky.app/profile/rladies-vienna.github.io) | [{{< fa brands linkedin title="LinkedIn">}} Linkedin](https://linkedin.com/company/r-ladies-vienna/)'

format:
  html:
    theme: [cosmos, styles.scss]
    toc: false 
    date-format: "D MMMM YYYY"

